version : '3.7'

services:
  web:
    build: ./assignment
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./assignment:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - web
    command: npm start

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=task_management
      - POSTGRES_PASSWORD=qwerty11
      - POSTGRES_DB=tasks

volumes:
  postgres_data: