# Generated by Django 3.0.2 on 2020-01-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Project',
            new_name='project',
        ),
    ]
