# Generated by Django 3.0.2 on 2020-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_auto_20200202_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
