# Generated by Django 3.0.2 on 2020-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_auto_20200202_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(max_length=120),
        ),
    ]
